[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]


[dev-packages]
mypy = "~= 0.57"
pytest = "~= 3.5.0"
ptpython = "*"
yapf = "*"


[requires]
python_version = "3.6"
