language: objective-c
osx_image: xcode7.1
xcode_project: {{_input_:project}}.xcodeproj
xcode_scheme:
    - {{_input_:project}}
xcode_sdk:
    - iphonesimulator9.1
before_install:
    - brew tap mitsuse/bullet
    - brew install bullet-cmd
    - brew install carthage
    - carthage bootstrap
after_success:
    - bullet send -t "Passed (${TRAVIS_BRANCH} at ${TRAVIS_REPO_SLUG})" -l "https://travis-ci.org/${TRAVIS_REPO_SLUG}/builds/${TRAVIS_BUILD_ID}"
after_failure:
    - bullet send -t "Failed (${TRAVIS_BRANCH} at ${TRAVIS_REPO_SLUG})" -l "https://travis-ci.org/${TRAVIS_REPO_SLUG}/builds/${TRAVIS_BUILD_ID}"
notifications:
    email:
        on_success: never
        on_failure: never
