#!/bin/bash

PID_SYSTEMD=$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{ print $2 }')
if [ -z "$PID_SYSTEMD" ]; then
    daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
fi