# save command history
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_dups
setopt hist_reduce_blanks
setopt share_history

# search history with history-search-end
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

# use vi-like keybinds and set the default editor to vim
bindkey -v
export EDITOR=vim

# misc
alias sudo='sudo '
alias tp='pyenv exec trash-put'
export PATH=$HOME/bin:$HOME/localenv/scripts:$PATH
autoload -U compinit && compinit
autoload -U predict-on && predict-on
setopt auto_cd

# load more specific config files
# for CONFIG_PATH in $HOME/.zshrc_*
# load .zshrc_other first
[ -f $HOME/.zshrc_other ] && source $HOME/.zshrc_other
for CONFIG_PATH in $(find $HOME -maxdepth 1 -name '.zshrc_*' ! -name '.zshrc_other')
do
    [ -f $CONFIG_PATH ] && source $CONFIG_PATH
done

# use a simple prompt
[ -f $HOME/.zshrc_git ] && source $HOME/.zshrc_git
autoload -U add-zsh-hook
autoload -U vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' formats '(%s) [%b]'

function update_vcs_info_msg() {
    psvar=()
    vcs_info   
    [[ -n "$vcs_info_msg_0_" ]] && psvar[1]="$vcs_info_msg_0_"
}

add-zsh-hook precmd update_vcs_info_msg

autoload -U colors && colors
PROMPT="%B%{${fg[yellow]}%}%~ %1(v|%v|)%b
%{${reset_color}%}[${USER}%B@${HOST}%b]$ "
