#!/usr/bin/env python
# coding: utf-8

def main(args):
    import os
    for path in args.path_seq:
        if os.path.exists(path):
            abspath = os.path.abspath(path)
            print('!! already exists: {}'.format(abspath))
        else:
            init_repository(path)


def init_repository(path):
    import os
    from git import Repo
    repo_path = os.path.join(path, 'repo')
    return Repo.init(repo_path)


def parse_args(args):
    import argparse
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('path_seq', metavar='PATH', nargs='+', type=str,
        help='the path of repository')
    return parser.parse_args(args)


if __name__ == '__main__':
    import sys
    main(parse_args(sys.argv[1:]))
