sudo: false
language: generic

install:
  - git clone --depth 1 https://github.com/sstephenson/bats.git

script:
  - PATH="./bats/bin:$PATH" test/run

notifications:
  slack:
    - secure: "YZ5q2CjTApNTX9OouIaxkJowGyjuVfbrC5Pj1Dt9unpr6P54FV+ehHpSUAJjtZ5MmjYi4yihAGuctGjs8toR7dw8ac4OePsoNcWru250Hhnl4X6Ozb0Vnb5lO1a8+wAFQTL3VJuPf2r4/Z1Zm9G6W+5E/gOeHSvslaHPLaeFf4ZFaH5W0ihHwcHDU/BYxyX7DHHduWaIIZoroSKb7M0U+QeOSDHZUNA7SysDP9XC+W7fx7t7NZqfFAU4KsTBaJNQwrBNAClsg3mty2d63xmUByDN3LiNICZajG9PvmxqT27IcNCXrhSNG9Hd/rA8mcJJ5eCV6kC7/RTayoMnL7GmOaB7fzpMe1VhEb/4mMxNQTF99kozawoQY+Zqlx3YqpmjLafOJCWjaZAdW4caK58HQdFERPW2DTFWvyKgB2g5WqPi/hfEP+w4xf3YyhM5wjP3x/qCNhNDS5VnpgWSPG2EhP0sY0EhOAjhhhc7F9CtGDulQZM5F+Rlk06xOU6C4/A12p9MJE/I+3rLzfN1xL4Her+W5iXm/GKXqqqnzv7zElqpG3Pbn43/9KVs1vX76CIvSZX8kFNxQQNq0KEtoHCvCq+beNIC6WYIC2wGQDsdphQEXnGwky/4/5DU66kJ2tM/n4iFnQJARZGDzufJxdtLY4WCWZbMXwBMm4Xz2swVrQQ="
